declare const styles: {
  readonly "animated": string;
  readonly "button": string;
  readonly "checkbox": string;
  readonly "checked": string;
  readonly "color": string;
  readonly "colorPicker": string;
  readonly "colorPreview": string;
  readonly "disabled": string;
  readonly "group": string;
  readonly "hue": string;
  readonly "iconButton": string;
  readonly "iconCheckbox": string;
  readonly "input": string;
  readonly "inputSelect": string;
  readonly "label": string;
  readonly "main": string;
  readonly "numberInput": string;
  readonly "numberInputLabel": string;
  readonly "open": string;
  readonly "pill": string;
  readonly "saturation": string;
  readonly "select": string;
  readonly "separator": string;
  readonly "slider": string;
  readonly "sliderProgress": string;
  readonly "sliderThumb": string;
  readonly "sliderTrack": string;
  readonly "toggle": string;
};
export = styles;

